# Generated by Django 3.1.6 on 2021-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='手机号', max_length=20, verbose_name='手机号')),
                ('password', models.CharField(help_text='密码', max_length=15, verbose_name='密码')),
                ('name', models.CharField(help_text='用户名', max_length=20, verbose_name='用户名')),
                ('identity', models.BooleanField(default=False, help_text='用户身份', verbose_name='用户身份')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='视频', upload_to='media/video', verbose_name='视频')),
                ('video_pic', models.ImageField(help_text='视频封面', upload_to='media/pic', verbose_name='视频封面')),
                ('video_desc', models.TextField(help_text='视频介绍', verbose_name='视频介绍')),
            ],
            options={
                'verbose_name': '视频管理',
                'verbose_name_plural': '视频管理',
            },
        ),
    ]
