# Generated by Django 3.1.6 on 2021-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210205_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='is_show',
            field=models.BooleanField(default=True, help_text='是否展示', verbose_name='是否展示'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_show',
            field=models.BooleanField(default=True, help_text='是否展示', verbose_name='是否展示'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_desc_en',
            field=models.TextField(help_text='视频介绍', null=True, verbose_name='视频介绍'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_desc_zh_hans',
            field=models.TextField(help_text='视频介绍', null=True, verbose_name='视频介绍'),
        ),
    ]
